import { SlashCommandBuilder, ChatInputCommandInteraction, EmbedBuilder } from 'discord.js';
import { ApiKeyModel } from '../../database/models/System';
import crypto from 'node:crypto';

function generateApiKey(): string {
  return `pk_${crypto.randomBytes(20).toString('hex')}`;
}

export default {
  data: new SlashCommandBuilder()
    .setName('apikey')
    .setDescription('Manage REST API keys for servers')
    .addSubcommand(sub =>
      sub.setName('generate')
        .setDescription('Generate an API key for a server')
        .addStringOption(o => o.setName('server_id').setDescription('Server ID').setRequired(true))
        .addStringOption(o => o.setName('note').setDescription('Optional label or note').setRequired(false)))
    .addSubcommand(sub =>
      sub.setName('revoke')
        .setDescription('Revoke an API key')
        .addStringOption(o => o.setName('key').setDescription('API key to revoke').setRequired(true)))
    .addSubcommand(sub =>
      sub.setName('list')
        .setDescription('List all active API keys'))
    .addSubcommand(sub =>
      sub.setName('check')
        .setDescription('Get info about an API key')
        .addStringOption(o => o.setName('key').setDescription('API key').setRequired(true))),
  category: 'Owner',
  accessTier: 'owner',
  async execute(interaction: ChatInputCommandInteraction) {
    const sub = interaction.options.getSubcommand();
    await interaction.deferReply({ ephemeral: true });

    if (sub === 'generate') {
      const guildId = interaction.options.getString('server_id', true);
      const key = generateApiKey();

      // One active key per server
      const existing = await ApiKeyModel.findOne({ guildId, revoked: false });
      if (existing) {
        return interaction.editReply({
          content: `⚠️ Server \`${guildId}\` already has an active API key (\`${existing.key.slice(0, 12)}...\`). Revoke it first.`,
        });
      }

      await ApiKeyModel.create({ guildId, key, createdBy: interaction.user.id });

      const embed = new EmbedBuilder()
        .setTitle('🔑 API Key Generated')
        .setColor('#00ff00')
        .addFields(
          { name: 'API Key', value: `\`\`\`\n${key}\n\`\`\``, inline: false },
          { name: '⚠️ Warning', value: 'This key will not be shown again. Copy it now.', inline: false },
          { name: 'Server ID', value: guildId, inline: true },
          { name: 'Created', value: `<t:${Math.floor(Date.now() / 1000)}:F>`, inline: true },
        )
        .setTimestamp()
        .setFooter({ text: `Generated by ${interaction.user.tag}` });

      return interaction.editReply({ embeds: [embed] });
    }

    if (sub === 'revoke') {
      const key = interaction.options.getString('key', true);
      const entry = await ApiKeyModel.findOneAndUpdate({ key }, { revoked: true }, { new: true });

      if (!entry) return interaction.editReply({ content: '❌ API key not found.' });
      return interaction.editReply({ content: `✅ API key \`${key.slice(0, 12)}...\` has been revoked.` });
    }

    if (sub === 'list') {
      const active = await ApiKeyModel.find({ revoked: false }).lean();

      if (active.length === 0) return interaction.editReply({ content: 'ℹ️ No active API keys.' });

      const lines = active.map((k: any) =>
        `• \`${k.key.slice(0, 12)}...\` — Server: \`${k.guildId}\`\n  Created <t:${Math.floor(new Date(k.createdAt).getTime() / 1000)}:R>${k.lastUsedAt ? ` • Last used <t:${Math.floor(new Date(k.lastUsedAt).getTime() / 1000)}:R>` : ''}`
      );

      const embed = new EmbedBuilder()
        .setTitle('🔑 Active API Keys')
        .setColor('#5865F2')
        .setDescription(lines.join('\n\n').slice(0, 4000))
        .setFooter({ text: `${active.length} active key(s)` })
        .setTimestamp();

      return interaction.editReply({ embeds: [embed] });
    }

    if (sub === 'check') {
      const key = interaction.options.getString('key', true);
      const entry = await ApiKeyModel.findOne({ key }).lean() as any;

      if (!entry) return interaction.editReply({ content: '❌ API key not found.' });

      const embed = new EmbedBuilder()
        .setTitle('🔑 API Key Info')
        .setColor(entry.revoked ? '#ff0000' : '#00ff00')
        .addFields(
          { name: 'Status', value: entry.revoked ? '❌ Revoked' : '✅ Active', inline: true },
          { name: 'Server ID', value: entry.guildId, inline: true },
          { name: 'Created By', value: `<@${entry.createdBy}>`, inline: true },
          { name: 'Created', value: `<t:${Math.floor(new Date(entry.createdAt).getTime() / 1000)}:F>`, inline: true },
          { name: 'Last Used', value: entry.lastUsedAt ? `<t:${Math.floor(new Date(entry.lastUsedAt).getTime() / 1000)}:R>` : 'Never', inline: true },
        )
        .setTimestamp();

      return interaction.editReply({ embeds: [embed] });
    }
  },
};
