import { PermissionFlagsBits, SlashCommandBuilder } from "discord.js";
import type { CommandDefinition } from "../../structures/types.js";
import { PremiumModel } from "../../database/models/Premium.js";
import { successEmbed, errorEmbed, baseEmbed } from "../../utils/embeds.js";

const command: CommandDefinition = {
  name: "premiumactivate",
  description: "Activate a premium code to unlock Premium features for this server",
  category: "Settings",
  access: "admin",
  memberPermissions: [PermissionFlagsBits.ManageGuild],
  guildOnly: true,
  cooldown: 10,
  aliases: ["activatepremium", "redeemcode"],
  slashData: (b) =>
    (b as SlashCommandBuilder)
      .addStringOption((o) => o.setName("code").setDescription("Premium activation code").setRequired(true)),
  async execute(ctx) {
    const guild = ctx.interaction?.guild ?? ctx.message?.guild;
    if (!guild) return;
    const code = ctx.isSlash ? ctx.interaction!.options.getString("code", true).toUpperCase().trim() : ctx.args[0]?.toUpperCase().trim();
    if (!code) { await ctx.reply({ embeds: [errorEmbed("Please provide an activation code.")] }); return; }

    const premiumRecord = await PremiumModel.findOne({ guildId: guild.id }).lean();
    if ((premiumRecord as any)?.tier && (premiumRecord as any).tier !== "none") {
      await ctx.reply({ embeds: [errorEmbed("This server already has an active Premium subscription.")] }); return;
    }

    // In a real deployment, codes are generated by the bot owner via /premiumgenerate.
    // Here we look up a valid, unclaimed code in the database.
    const codeRecord = await (PremiumModel as any).findOne?.({ activationCode: code, activationUsed: false }) ?? null;

    if (!codeRecord) {
      await ctx.reply({ embeds: [errorEmbed("Invalid or already-used activation code. Please check the code and try again.")] }); return;
    }

    await PremiumModel.findOneAndUpdate(
      { guildId: guild.id },
      {
        $set: {
          tier: (codeRecord as any).tier ?? "standard",
          activatedAt: new Date(),
          activatedBy: ctx.userId,
          expiresAt: null,
        },
      },
      { upsert: true },
    );

    // Mark code as used
    await (PremiumModel as any).updateOne?.({ activationCode: code }, { $set: { activationUsed: true, usedByGuildId: guild.id } });

    const embed = baseEmbed("premium")
      .setTitle("⭐ Premium Activated!")
      .setDescription(`**${guild.name}** now has **${((codeRecord as any).tier ?? "Standard").toUpperCase()} Premium**.\n\nAll premium features are now unlocked. Type \`premium status\` to see what's available.`);

    await ctx.reply({ embeds: [embed] });
  },
};
export default command;
